# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('handler', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64)),
                ('expiration_dt', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.Action')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.Actor')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.Case')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('initial', models.BooleanField(default=False)),
                ('template_func', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='stately.Workflow'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.State'),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.State'),
        ),
        migrations.AddField(
            model_name='case',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.Workflow'),
        ),
        migrations.AddField(
            model_name='actor',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stately.Case'),
        ),
        migrations.AddField(
            model_name='action',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='stately.State'),
        ),
    ]
