# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('slug', 'workflow')]),
        ),
    ]
