# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 19:25
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0003_match_new_workflow_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='context',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
