# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0004_allow_null_workflow_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stately.Action'),
        ),
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stately.Actor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stately.Case'),
        ),
    ]
