# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0007_add_relational_fields_to_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='expiration_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
