# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def uniquely_slugify(value, unique_within_qs, uniquify=None, **kwargs):
    """
    Adapted from stately.models as of commit
    e27562928bee1bffd01910e93ceaa9de80701a91
    """
    # Initialize count and uniquify
    count = 0
    if uniquify is None:
        uniquify = lambda initial, x: initial + str(x)

    # Create an initial slug
    initial_slug = slug = slugify(value, **kwargs)

    # Check whether the slug is used. Try to uniquify it if it is.
    while unique_within_qs.filter(slug=slug).exists():
        count += 1
        slug = uniquify(initial_slug, count)

    return slug


def populate_action_slugs(apps, schema):
    Action = apps.get_model('stately', 'Action')
    for action in Action.objects.all().select_related('state').prefetch_related('state__actions'):
        action.slug = uniquely_slugify(action.name, action.state.actions.all())
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0009_create_assignment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='slug',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_action_slugs,
            migrations.RunPython.noop,
        ),
    ]
