# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0011_make_action_slugs_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='state',
            new_name='current_state',
        ),
    ]
