# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Forward
def delete_anonymous_actors(apps, schema):
    Actor = apps.get_model('stately', 'Actor')
    
    Actor.objects.filter(email=None).delete()


# Reverse
def create_anonymous_actors(apps, schema):
    Actor = apps.get_model('stately', 'Actor')
    Assignment = apps.get_model('stately', 'Assignment')

    for assignment in Assignment.objects.filter(actor=None):
        assignment.actor = Actor.objects.create()
        assignment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0013_allow_actor_email_to_be_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stately.Actor'),
        ),
        migrations.RunPython(
            delete_anonymous_actors,
            create_anonymous_actors,
        ),
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
