# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0015_add_assignment_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
