# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0017_actorauthenticator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actorauthenticator',
            old_name='generated_at',
            new_name='generated_dt',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='expiration_dt',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='token',
        ),
    ]
