# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0018_remove_token_from_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
