# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stately', '0020_assignment_assigned_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
